apiVersion: v1
kind: Namespace
metadata:
  name: FILLED_IN_BY_CI
  labels:
    sandboxId: FILLED_IN_BY_CI
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: FILLED_IN_BY_CI
  namespace: FILLED_IN_BY_CI
spec:
  interval: 5m0s
  url: FILLED_IN_BY_CI
  ref:
    branch: FILLED_IN_BY_CI
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: FILLED_IN_BY_CI
  namespace: FILLED_IN_BY_CI
spec:
  image: FILLED_IN_BY_CI
  interval: 2m0s
  provider: aws
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: FILLED_IN_BY_CI
  namespace: FILLED_IN_BY_CI
spec:
  imageRepositoryRef:
    name: FILLED_IN_BY_CI
  filterTags:
    pattern: FILLED_IN_BY_CI
    extract: FILLED_IN_BY_CI
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageUpdateAutomation
metadata:
  name: FILLED_IN_BY_CI
  namespace: FILLED_IN_BY_CI
spec:
  interval: 2m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  git:
    commit:
      author:
        name: Flux - API image update
        email: ci@biomage.net
  update:
    strategy: Setters
    path: FILLED_IN_BY_CI
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: FILLED_IN_BY_CI
  namespace: FILLED_IN_BY_CI
  labels:
    sandboxId: FILLED_IN_BY_CI
spec:
  releaseName: FILLED_IN_BY_CI
  interval: 2m0s
  chart:
    spec:
      chart: charts/nodejs
      sourceRef:
        kind: GitRepository
        name: FILLED_IN_BY_CI
        namespace: FILLED_IN_BY_CI
      reconcileStrategy: Revision
  values:
    service:
      externalPort: 3000
      internalPort: 3000
    readinessProbe:
      path: "/v2/health"
    livenessProbe:
      probeType: tcpSocket
    resources:
      requests:
        cpu: "100m"
    hpa:
      enabled: false
    loadBalancerHealthCheck:
      path: "/"
  valuesFrom:
    - kind: ConfigMap
      name: account-config
      valuesKey: account-config.yaml
      optional: false
# filled in by CI. do not modify.
