# install types for our libraries

npm install @types/kubernetes/client-node --save-dev
npm install @types/async-lock --save-dev
npm install @types/aws-sdk --save-dev
npm install @types/aws-sdk-mock --save-dev
npm install @types/aws-xray-sdk --save-dev
npm install @types/babel-cli --save-dev
npm install @types/babel-core --save-dev
npm install @types/babel-eslint --save-dev
npm install @types/body-parser --save-dev
npm install @types/cors --save-dev
npm install @types/dotenv --save-dev
npm install @types/eslint --save-dev
npm install @types/eslint-config-airbnb-base --save-dev
npm install @types/eslint-plugin-import --save-dev
npm install @types/express --save-dev
npm install @types/express-jwt --save-dev
npm install @types/express-openapi-validator --save-dev
npm install @types/github-download-directory --save-dev
npm install @types/ioredis --save-dev
npm install @types/ioredis-mock --save-dev
npm install @types/jest --save-dev
npm install @types/jest-fetch-mock --save-dev
npm install @types/js-yaml --save-dev
npm install @types/jsonwebtoken --save-dev
npm install @types/jwk-to-pem --save-dev
npm install @types/lodash --save-dev
npm install @types/log-timestamp --save-dev
npm install @types/lru-cache --save-dev
npm install @types/micromatch --save-dev
npm install @types/node-cleanup --save-dev
npm install @types/node-fetch --save-dev
npm install @types/node-jq --save-dev
npm install @types/nodemon --save-dev
npm install @types/object-hash --save-dev
npm install @types/pre-commit --save-dev
npm install @types/sns-validator --save-dev
npm install @types/socket.io --save-dev
npm install @types/socket.io-client --save-dev
npm install @types/socket.io-mock --save-dev
npm install @types/socket.io-redis --save-dev
npm install @types/supertest --save-dev
npm install @types/swagger-client --save-dev
npm install @types/swagger-model-validator --save-dev
npm install @types/uuid --save-dev
npm install @types/yaml --save-dev