title: Number of genes vs UMIs
type: object
description: Processing config body for Number of genes vs UMIs filter.
properties:
  enabled:
    type: boolean
  auto:
    type: boolean
  filterSettings:
    type: object
    properties:
      regressionType:
        type: string
        minLength: 1
      regressionTypeSettings:
        type: object
        properties:
          p.level:
            type: number
required:
  - filterSettings
