title: Cell Size Distribution
type: object
description: Processing config body for Cell Size Distribution filter. Keys are sample UUIDs or 'one' for Seurat uploads, values are per-sample configurations.
additionalProperties:
  type: object
  properties:
    enabled:
      type: boolean
    auto:
      type: boolean
    filterSettings:
      type: object
      properties:
        minCellSize:
          oneOf:
            - type: number
            - type: array
              items:
                type: number
        binStep:
          type: number
    defaultFilterSettings:
      type: object
      properties:
        minCellSize:
          type: number
        binStep:
          type: number
  required:
    - filterSettings