const fullHistory = [
  {
    type: 'ExecutionStarted',
    id: 1,
    previousEventId: 0,
  },
  {
    type: 'Dummy',
    id: 'dummy-state-having-zero-as-previous',
    previousEventId: 0,
  },
  {
    type: 'MapStateEntered',
    id: 12,
    previousEventId: 'dummy-state-having-zero-as-previous',
    stateEnteredEventDetails: {
      name: 'Filters',
    },
  },
  {
    type: 'MapStateStarted',
    id: 13,
    previousEventId: 12,
    mapStateStartedEventDetails: {
      length: 2,
    },
  },
  {
    type: 'MapIterationStarted',
    id: 14,
    previousEventId: 13,
    mapIterationStartedEventDetails: {
      name: 'Filters',
      index: 0,
    },
  },
  {
    // Iteration 0
    type: 'TaskStateEntered',
    id: 15,
    previousEventId: 14,
    stateEnteredEventDetails: {
      name: 'CellSizeDistributionFilter',
    },
  },
  {
    // Iteration 0
    type: 'TaskSucceeded',
    id: 16,
    previousEventId: 15,
  },
  {
    // Iteration 0
    type: 'TaskStateExited',
    id: 17,
    previousEventId: 16,
    stateExitedEventDetails: {
      name: 'CellSizeDistributionFilter',
    },
  },
  {
    type: 'MapIterationStarted',
    id: 18,
    previousEventId: 13,
    mapIterationStartedEventDetails: {
      name: 'Filters',
      index: 1,
    },
  },
  {
    // Iteration 0
    type: 'TaskStateEntered',
    id: '19-before-anything-completed',
    previousEventId: 17,
    stateEnteredEventDetails: {
      name: 'MitochondrialContentFilter',
    },
  },
  {
    // Iteration 0
    type: 'TaskSucceeded',
    id: '20-one-comlpetion-vs-unstarted',
    previousEventId: '19-before-anything-completed',
  },
  {
    // Iteration 1
    type: 'TaskStateEntered',
    id: 21,
    previousEventId: 18,
    stateEnteredEventDetails: {
      name: 'CellSizeDistributionFilter',
    },
  },
  {
    // Iteration 0
    type: 'TaskStateExited',
    id: 22,
    previousEventId: '20-one-comlpetion-vs-unstarted',
    stateExitedEventDetails: {
      name: 'MitochondrialContentFilter',
    },
  },
  {
    // Iteration 1
    type: 'TaskSucceeded',
    id: 23,
    previousEventId: 21,
  },
  {
    // Iteration 1
    type: 'TaskStateExited',
    id: '24-two-completions-vs-one',
    previousEventId: 23,
    stateExitedEventDetails: {
      name: 'CellSizeDistributionFilter',
    },
  },
  {
    // Iteration 1
    type: 'TaskStateEntered',
    id: 25,
    previousEventId: '24-two-completions-vs-one',
    stateEnteredEventDetails: {
      name: 'MitochondrialContentFilter',
    },
  },
  {
    // Iteration 1
    type: 'TaskSucceeded',
    id: 26,
    previousEventId: 25,
  },
  {
    // Iteration 1
    type: 'TaskStateExited',
    id: 27,
    previousEventId: 26,
    stateExitedEventDetails: {
      name: 'MitochondrialContentFilter',
    },
  },
  {
    // Iteration 1
    type: 'MapIterationSucceeded',
    id: 28,
    previousEventId: 27,
    mapIterationSucceededEventDetails: {
      name: 'Filters',
      index: 1,
    },
  },
  {
    // Iteration 0
    type: 'MapIterationSucceeded',
    id: 29,
    previousEventId: 22,
    mapIterationSucceededEventDetails: {
      name: 'Filters',
      index: 0,
    },
  },
  {
    type: 'MapStateSucceeded',
    id: 30,
    previousEventId: 29,
  },
  {
    type: 'MapStateExited',
    id: 31,
    previousEventId: 30,
    stateExitedEventDetails: {
      name: 'Filters',
    },
  },
  {
    type: 'TaskStateEntered',
    id: 32,
    previousEventId: 31,
    stateEnteredEventDetails: {
      name: 'DataIntegration',
    },
  },
  {
    type: 'TaskSucceeded',
    id: 33,
    previousEventId: 32,
  },
  {
    type: 'TaskStateExited',
    id: 34,
    previousEventId: 33,
    stateExitedEventDetails: {
      name: 'DataIntegration',
    },
  },
];

const singleIterationHistory = [
  {
    type: 'ExecutionStarted',
    id: 1,
    previousEventId: 0,
  },
  {
    type: 'Dummy',
    id: 'dummy-state-having-zero-as-previous',
    previousEventId: 0,
  },
  {
    type: 'MapStateEntered',
    id: 12,
    previousEventId: 'dummy-state-having-zero-as-previous',
    stateEnteredEventDetails: {
      name: 'Filters',
    },
  },
  {
    type: 'MapStateStarted',
    id: 13,
    previousEventId: 12,
    mapStateStartedEventDetails: {
      length: 1,
    },
  },
  {
    type: 'MapIterationStarted',
    id: 14,
    previousEventId: 13,
    mapIterationStartedEventDetails: {
      name: 'Filters',
      index: 0,
    },
  },
  {
    type: 'TaskStateEntered',
    id: 15,
    previousEventId: 14,
    stateEnteredEventDetails: {
      name: 'CellSizeDistributionFilter',
    },
  },
  {
    type: 'TaskSucceeded',
    id: 16,
    previousEventId: 15,
  },
  {
    type: 'TaskStateExited',
    id: 17,
    previousEventId: 16,
    stateExitedEventDetails: {
      name: 'CellSizeDistributionFilter',
    },
  },
  {
    type: 'MapIterationSucceeded',
    id: 18,
    previousEventId: 17,
    mapIterationSucceededEventDetails: {
      name: 'Filters',
      index: 0,
    },
  },
  {
    type: 'MapStateSucceeded',
    id: 19,
    previousEventId: 18,
  },
  {
    type: 'MapStateExited',
    id: 20,
    previousEventId: 19,
    stateExitedEventDetails: {
      name: 'Filters',
    },
  },
  {
    type: 'TaskStateEntered',
    id: 21,
    previousEventId: 20,
    stateEnteredEventDetails: {
      name: 'DataIntegration',
    },
  },
  {
    type: 'TaskSucceeded',
    id: 22,
    previousEventId: 21,
  },
  {
    type: 'TaskStateExited',
    id: 23,
    previousEventId: 22,
    stateExitedEventDetails: {
      name: 'DataIntegration',
    },
  },
];

const noPodsToDeleteHistory = [
  {
    timestamp: '2021-08-31T17:12:58.495Z',
    type: 'ExecutionStarted',
    id: 1,
    previousEventId: 0,
    executionStartedEventDetails: {
      roleArn: 'arn:aws:iam::19610412:role/state-machine-role-staging',
    },
  },
  {
    timestamp: '2021-08-31T17:12:58.536Z',
    type: 'TaskStateEntered',
    id: 2,
    previousEventId: 0,
    stateEnteredEventDetails: { name: 'GetExperimentRunningPods' },
  },
  {
    timestamp: '2021-08-31T17:12:58.536Z',
    type: 'TaskScheduled',
    id: 3,
    previousEventId: 2,
    taskScheduledEventDetails: {
      resourceType: 'eks',
      resource: 'call',
      region: 'some-region-in-eu',
      parameters: 'test',
    },
  },
  {
    timestamp: '2021-08-31T17:12:58.567Z',
    type: 'TaskStarted',
    id: 4,
    previousEventId: 3,
    taskStartedEventDetails: { resourceType: 'eks', resource: 'call' },
  },
  {
    timestamp: '2021-08-31T17:12:58.630Z',
    type: 'TaskSucceeded',
    id: 5,
    previousEventId: 4,
    taskSucceededEventDetails: { resourceType: 'eks', resource: 'call' },
  },
  {
    timestamp: '2021-08-31T17:12:58.630Z',
    type: 'TaskStateExited',
    id: 6,
    previousEventId: 5,
    stateExitedEventDetails: { name: 'GetExperimentRunningPods' },
  },
  {
    timestamp: '2021-08-31T17:12:58.684Z',
    type: 'MapStateEntered',
    id: 7,
    previousEventId: 6,
    stateEnteredEventDetails: { name: 'DeletePreviousPods' },
  },
  {
    timestamp: '2021-08-31T17:12:58.684Z',
    type: 'MapStateStarted',
    id: 8,
    previousEventId: 7,
    mapStateStartedEventDetails: { length: 0 },
  },
  {
    timestamp: '2021-08-31T17:12:58.684Z',
    type: 'MapStateSucceeded',
    id: 9,
    previousEventId: 8,
  },
  {
    timestamp: '2021-08-31T17:12:58.684Z',
    type: 'MapStateExited',
    id: 10,
    previousEventId: 8,
    stateExitedEventDetails: { name: 'DeletePreviousPods' },
  },
  {
    timestamp: '2021-08-31T17:12:58.785Z',
    type: 'MapStateEntered',
    id: 11,
    previousEventId: 10,
    stateEnteredEventDetails: { name: 'AssignPipelineToPod' },
  },
  {
    timestamp: '2021-08-31T17:12:58.785Z',
    type: 'MapStateStarted',
    id: 12,
    previousEventId: 11,
    mapStateStartedEventDetails: { length: 1 },
  },
  {
    timestamp: '2021-08-31T17:12:58.785Z',
    type: 'MapIterationStarted',
    id: 13,
    previousEventId: 12,
    mapIterationStartedEventDetails: { name: 'AssignPipelineToPod', index: 0 },
  },
  {
    timestamp: '2021-08-31T17:12:58.887Z',
    type: 'TaskStateEntered',
    id: 14,
    previousEventId: 13,
    stateEnteredEventDetails: { name: 'GetUnassignedPod' },
  },
  {
    timestamp: '2021-08-31T17:12:58.887Z',
    type: 'TaskScheduled',
    id: 15,
    previousEventId: 14,
    taskScheduledEventDetails: {
      resourceType: 'eks',
      resource: 'call',
      region: 'some-region-in-eu',
      parameters: '{"ClusterName":"green-cluster","CertificateAuthority":"real-certificate","Endpoint":"https://the-one-true-endpoint.com","Method":"GET","Path":"/api/v1/namespaces/thats-namespace-for-you/pods","QueryParameters":{"labelSelector":["!activityId,type=pipeline"],"fieldSelector":["status.phase=Running"]}}',
    },
  },
  {
    timestamp: '2021-08-31T17:12:58.898Z',
    type: 'TaskStarted',
    id: 16,
    previousEventId: 15,
    taskStartedEventDetails: { resourceType: 'eks', resource: 'call' },
  },
  {
    timestamp: '2021-08-31T17:12:58.959Z',
    type: 'TaskSucceeded',
    id: 17,
    previousEventId: 16,
    taskSucceededEventDetails: { resourceType: 'eks', resource: 'call' },
  },
  {
    timestamp: '2021-08-31T17:12:58.959Z',
    type: 'TaskStateExited',
    id: 18,
    previousEventId: 17,
    stateExitedEventDetails: { name: 'GetUnassignedPod' },
  },
  {
    timestamp: '2021-08-31T17:12:58.988Z',
    type: 'ChoiceStateEntered',
    id: 19,
    previousEventId: 18,
    stateEnteredEventDetails: { name: 'IsPodAvailable' },
  },
  {
    timestamp: '2021-08-31T17:12:58.988Z',
    type: 'ChoiceStateExited',
    id: 20,
    previousEventId: 19,
    stateExitedEventDetails: { name: 'IsPodAvailable' },
  },
  {
    timestamp: '2021-08-31T17:12:59.112Z',
    type: 'TaskStateEntered',
    id: 21,
    previousEventId: 20,
    stateEnteredEventDetails: { name: 'AssignPodToPipeline' },
  },
  {
    timestamp: '2021-08-31T17:12:59.112Z',
    type: 'TaskScheduled',
    id: 22,
    previousEventId: 21,
    taskScheduledEventDetails: {
      resourceType: 'eks',
      resource: 'call',
      region: 'some-region-in-eu',
      parameters: '{"ClusterName":"green-cluster","CertificateAuthority":"real-certificate","Endpoint":"https://the-one-true-endpoint.com","Method":"PATCH","RequestBody":{"metadata":{"labels":{"activityId":"some-life-pipeline","experimentId":"bfe61d3617f18d325a4bdf06f34a6d89","processName":"qc"}}},"Path":"/api/v1/namespaces/thats-namespace-for-you/pods/pipeline-64f75d6796-kvjnb"}',
    },
  },
  {
    timestamp: '2021-08-31T17:12:59.130Z',
    type: 'TaskStarted',
    id: 23,
    previousEventId: 22,
    taskStartedEventDetails: { resourceType: 'eks', resource: 'call' },
  },
  {
    timestamp: '2021-08-31T17:12:59.179Z',
    type: 'TaskSucceeded',
    id: 24,
    previousEventId: 23,
    taskSucceededEventDetails: { resourceType: 'eks', resource: 'call' },
  },
  {
    timestamp: '2021-08-31T17:12:59.179Z',
    type: 'TaskStateExited',
    id: 25,
    previousEventId: 24,
    stateExitedEventDetails: { name: 'AssignPodToPipeline' },
  },
  {
    timestamp: '2021-08-31T17:12:59.179Z',
    type: 'MapIterationSucceeded',
    id: 26,
    previousEventId: 25,
    mapIterationSucceededEventDetails: { name: 'AssignPipelineToPod', index: 0 },
  },
  {
    timestamp: '2021-08-31T17:12:59.179Z',
    type: 'MapStateSucceeded',
    id: 27,
    previousEventId: 26,
  },
  {
    timestamp: '2021-08-31T17:12:59.179Z',
    type: 'MapStateExited',
    id: 28,
    previousEventId: 26,
    stateExitedEventDetails: { name: 'AssignPipelineToPod' },
  },
  {
    timestamp: '2021-08-31T17:12:59.190Z',
    type: 'MapStateEntered',
    id: 29,
    previousEventId: 28,
    stateEnteredEventDetails: { name: 'ClassifierFilterMap' },
  },
  {
    timestamp: '2021-08-31T17:12:59.190Z',
    type: 'MapStateStarted',
    id: 30,
    previousEventId: 29,
    mapStateStartedEventDetails: { length: 3 },
  },
  {
    timestamp: '2021-08-31T17:12:59.190Z',
    type: 'MapIterationStarted',
    id: 31,
    previousEventId: 30,
    mapIterationStartedEventDetails: { name: 'ClassifierFilterMap', index: 0 },
  },
  {
    timestamp: '2021-08-31T17:12:59.190Z',
    type: 'MapIterationStarted',
    id: 32,
    previousEventId: 30,
    mapIterationStartedEventDetails: { name: 'ClassifierFilterMap', index: 1 },
  },
  {
    timestamp: '2021-08-31T17:12:59.190Z',
    type: 'MapIterationStarted',
    id: 33,
    previousEventId: 30,
    mapIterationStartedEventDetails: { name: 'ClassifierFilterMap', index: 2 },
  },
  {
    timestamp: '2021-08-31T17:12:59.291Z',
    type: 'TaskStateEntered',
    id: 34,
    previousEventId: 31,
    stateEnteredEventDetails: { name: 'ClassifierFilter' },
  },
  {
    timestamp: '2021-08-31T17:12:59.291Z',
    type: 'ActivityScheduled',
    id: 35,
    previousEventId: 34,
    activityScheduledEventDetails: {
      resource: 'arn:aws:states:some-region-in-eu:19610412:activity:some-life-pipeline',
      timeoutInSeconds: 10800,
    },
  },
  {
    timestamp: '2021-08-31T17:12:59.302Z',
    type: 'TaskStateEntered',
    id: 36,
    previousEventId: 32,
    stateEnteredEventDetails: { name: 'ClassifierFilter' },
  },
  {
    timestamp: '2021-08-31T17:12:59.302Z',
    type: 'ActivityScheduled',
    id: 37,
    previousEventId: 36,
    activityScheduledEventDetails: {
      resource: 'arn:aws:states:some-region-in-eu:19610412:activity:some-life-pipeline',
      timeoutInSeconds: 10800,
    },
  },
  {
    timestamp: '2021-08-31T17:12:59.311Z',
    type: 'TaskStateEntered',
    id: 38,
    previousEventId: 33,
    stateEnteredEventDetails: { name: 'ClassifierFilter' },
  },
  {
    timestamp: '2021-08-31T17:12:59.311Z',
    type: 'ActivityScheduled',
    id: 39,
    previousEventId: 38,
    activityScheduledEventDetails: {
      resource: 'arn:aws:states:some-region-in-eu:19610412:activity:some-life-pipeline',
      timeoutInSeconds: 10800,
    },
  },
  {
    timestamp: '2021-08-31T17:13:05.475Z',
    type: 'ActivityStarted',
    id: 40,
    previousEventId: 37,
    activityStartedEventDetails: { workerName: 'local' },
  },
  {
    timestamp: '2021-08-31T17:15:27.820Z',
    type: 'ActivitySucceeded',
    id: 41,
    previousEventId: 40,
    activitySucceededEventDetails: {},
  },
  {
    timestamp: '2021-08-31T17:15:27.820Z',
    type: 'TaskStateExited',
    id: 42,
    previousEventId: 41,
    stateExitedEventDetails: { name: 'ClassifierFilter' },
  },
  {
    timestamp: '2021-08-31T17:15:27.820Z',
    type: 'MapIterationSucceeded',
    id: 43,
    previousEventId: 42,
    mapIterationSucceededEventDetails: { name: 'ClassifierFilterMap', index: 1 },
  },
  {
    timestamp: '2021-08-31T17:15:27.895Z',
    type: 'ActivityStarted',
    id: 44,
    previousEventId: 35,
    activityStartedEventDetails: { workerName: 'local' },
  },
  {
    timestamp: '2021-08-31T17:16:10.478Z',
    type: 'ActivitySucceeded',
    id: 45,
    previousEventId: 44,
    activitySucceededEventDetails: {},
  },
  {
    timestamp: '2021-08-31T17:16:10.478Z',
    type: 'TaskStateExited',
    id: 46,
    previousEventId: 45,
    stateExitedEventDetails: { name: 'ClassifierFilter' },
  },
  {
    timestamp: '2021-08-31T17:16:10.478Z',
    type: 'MapIterationSucceeded',
    id: 47,
    previousEventId: 46,
    mapIterationSucceededEventDetails: { name: 'ClassifierFilterMap', index: 0 },
  },
  {
    timestamp: '2021-08-31T17:16:10.551Z',
    type: 'ActivityStarted',
    id: 48,
    previousEventId: 39,
    activityStartedEventDetails: { workerName: 'local' },
  },
  {
    timestamp: '2021-08-31T17:16:55.843Z',
    type: 'ActivitySucceeded',
    id: 49,
    previousEventId: 48,
    activitySucceededEventDetails: {},
  },
  {
    timestamp: '2021-08-31T17:16:55.843Z',
    type: 'TaskStateExited',
    id: 50,
    previousEventId: 49,
    stateExitedEventDetails: { name: 'ClassifierFilter' },
  },
  {
    timestamp: '2021-08-31T17:16:55.843Z',
    type: 'MapIterationSucceeded',
    id: 51,
    previousEventId: 50,
    mapIterationSucceededEventDetails: { name: 'ClassifierFilterMap', index: 2 },
  },
  {
    timestamp: '2021-08-31T17:16:55.843Z',
    type: 'MapStateSucceeded',
    id: 52,
    previousEventId: 51,
  },
  {
    timestamp: '2021-08-31T17:16:55.843Z',
    type: 'MapStateExited',
    id: 53,
    previousEventId: 51,
    stateExitedEventDetails: { name: 'ClassifierFilterMap' },
  },
  {
    timestamp: '2021-08-31T17:16:55.861Z',
    type: 'MapStateEntered',
    id: 54,
    previousEventId: 53,
    stateEnteredEventDetails: { name: 'CellSizeDistributionFilterMap' },
  },
  {
    timestamp: '2021-08-31T17:16:55.861Z',
    type: 'MapStateStarted',
    id: 55,
    previousEventId: 54,
    mapStateStartedEventDetails: { length: 3 },
  },
  {
    timestamp: '2021-08-31T17:16:55.861Z',
    type: 'MapIterationStarted',
    id: 56,
    previousEventId: 55,
    mapIterationStartedEventDetails: { name: 'CellSizeDistributionFilterMap', index: 0 },
  },
  {
    timestamp: '2021-08-31T17:16:55.861Z',
    type: 'MapIterationStarted',
    id: 57,
    previousEventId: 55,
    mapIterationStartedEventDetails: { name: 'CellSizeDistributionFilterMap', index: 1 },
  },
  {
    timestamp: '2021-08-31T17:16:55.861Z',
    type: 'MapIterationStarted',
    id: 58,
    previousEventId: 55,
    mapIterationStartedEventDetails: { name: 'CellSizeDistributionFilterMap', index: 2 },
  },
  {
    timestamp: '2021-08-31T17:16:55.963Z',
    type: 'TaskStateEntered',
    id: 59,
    previousEventId: 56,
    stateEnteredEventDetails: { name: 'CellSizeDistributionFilter' },
  },
  {
    timestamp: '2021-08-31T17:16:55.963Z',
    type: 'ActivityScheduled',
    id: 60,
    previousEventId: 59,
    activityScheduledEventDetails: {
      resource: 'arn:aws:states:some-region-in-eu:19610412:activity:some-life-pipeline',
      timeoutInSeconds: 10800,
    },
  },
  {
    timestamp: '2021-08-31T17:16:55.977Z',
    type: 'TaskStateEntered',
    id: 61,
    previousEventId: 57,
    stateEnteredEventDetails: { name: 'CellSizeDistributionFilter' },
  },
  {
    timestamp: '2021-08-31T17:16:55.977Z',
    type: 'ActivityScheduled',
    id: 62,
    previousEventId: 61,
    activityScheduledEventDetails: {
      resource: 'arn:aws:states:some-region-in-eu:19610412:activity:some-life-pipeline',
      timeoutInSeconds: 10800,
    },
  },
  {
    timestamp: '2021-08-31T17:16:55.985Z',
    type: 'TaskStateEntered',
    id: 63,
    previousEventId: 58,
    stateEnteredEventDetails: { name: 'CellSizeDistributionFilter' },
  },
  {
    timestamp: '2021-08-31T17:16:55.985Z',
    type: 'ActivityScheduled',
    id: 64,
    previousEventId: 63,
    activityScheduledEventDetails: {
      resource: 'arn:aws:states:some-region-in-eu:19610412:activity:some-life-pipeline',
      timeoutInSeconds: 10800,
    },
  },
  {
    timestamp: '2021-08-31T17:16:56.026Z',
    type: 'ActivityStarted',
    id: 65,
    previousEventId: 60,
    activityStartedEventDetails: { workerName: 'local' },
  },
  {
    timestamp: '2021-08-31T17:17:25.222Z',
    type: 'ActivitySucceeded',
    id: 66,
    previousEventId: 65,
    activitySucceededEventDetails: {},
  },
  {
    timestamp: '2021-08-31T17:17:25.222Z',
    type: 'TaskStateExited',
    id: 67,
    previousEventId: 66,
    stateExitedEventDetails: { name: 'CellSizeDistributionFilter' },
  },
  {
    timestamp: '2021-08-31T17:17:25.222Z',
    type: 'MapIterationSucceeded',
    id: 68,
    previousEventId: 67,
    mapIterationSucceededEventDetails: { name: 'CellSizeDistributionFilterMap', index: 0 },
  },
  {
    timestamp: '2021-08-31T17:17:25.293Z',
    type: 'ActivityStarted',
    id: 69,
    previousEventId: 62,
    activityStartedEventDetails: { workerName: 'local' },
  },
  {
    timestamp: '2021-08-31T17:17:56.453Z',
    type: 'ActivitySucceeded',
    id: 70,
    previousEventId: 69,
    activitySucceededEventDetails: {},
  },
  {
    timestamp: '2021-08-31T17:17:56.453Z',
    type: 'TaskStateExited',
    id: 71,
    previousEventId: 70,
    stateExitedEventDetails: { name: 'CellSizeDistributionFilter' },
  },
  {
    timestamp: '2021-08-31T17:17:56.453Z',
    type: 'MapIterationSucceeded',
    id: 72,
    previousEventId: 71,
    mapIterationSucceededEventDetails: { name: 'CellSizeDistributionFilterMap', index: 1 },
  },
  {
    timestamp: '2021-08-31T17:17:56.547Z',
    type: 'ActivityStarted',
    id: 73,
    previousEventId: 64,
    activityStartedEventDetails: { workerName: 'local' },
  },
  {
    timestamp: '2021-08-31T17:18:29.384Z',
    type: 'ActivitySucceeded',
    id: 74,
    previousEventId: 73,
    activitySucceededEventDetails: {},
  },
  {
    timestamp: '2021-08-31T17:18:29.384Z',
    type: 'TaskStateExited',
    id: 75,
    previousEventId: 74,
    stateExitedEventDetails: { name: 'CellSizeDistributionFilter' },
  },
  {
    timestamp: '2021-08-31T17:18:29.384Z',
    type: 'MapIterationSucceeded',
    id: 76,
    previousEventId: 75,
    mapIterationSucceededEventDetails: { name: 'CellSizeDistributionFilterMap', index: 2 },
  },
  {
    timestamp: '2021-08-31T17:18:29.384Z',
    type: 'MapStateSucceeded',
    id: 77,
    previousEventId: 76,
  },
  {
    timestamp: '2021-08-31T17:18:29.384Z',
    type: 'MapStateExited',
    id: 78,
    previousEventId: 76,
    stateExitedEventDetails: { name: 'CellSizeDistributionFilterMap' },
  },
  {
    timestamp: '2021-08-31T17:18:29.400Z',
    type: 'MapStateEntered',
    id: 79,
    previousEventId: 78,
    stateEnteredEventDetails: { name: 'MitochondrialContentFilterMap' },
  },
  {
    timestamp: '2021-08-31T17:18:29.400Z',
    type: 'MapStateStarted',
    id: 80,
    previousEventId: 79,
    mapStateStartedEventDetails: { length: 3 },
  },
  {
    timestamp: '2021-08-31T17:18:29.400Z',
    type: 'MapIterationStarted',
    id: 81,
    previousEventId: 80,
    mapIterationStartedEventDetails: { name: 'MitochondrialContentFilterMap', index: 0 },
  },
  {
    timestamp: '2021-08-31T17:18:29.400Z',
    type: 'MapIterationStarted',
    id: 82,
    previousEventId: 80,
    mapIterationStartedEventDetails: { name: 'MitochondrialContentFilterMap', index: 1 },
  },
  {
    timestamp: '2021-08-31T17:18:29.400Z',
    type: 'MapIterationStarted',
    id: 83,
    previousEventId: 80,
    mapIterationStartedEventDetails: { name: 'MitochondrialContentFilterMap', index: 2 },
  },
  {
    timestamp: '2021-08-31T17:18:29.502Z',
    type: 'TaskStateEntered',
    id: 84,
    previousEventId: 81,
    stateEnteredEventDetails: { name: 'MitochondrialContentFilter' },
  },
  {
    timestamp: '2021-08-31T17:18:29.502Z',
    type: 'ActivityScheduled',
    id: 85,
    previousEventId: 84,
    activityScheduledEventDetails: {
      resource: 'arn:aws:states:some-region-in-eu:19610412:activity:some-life-pipeline',
      timeoutInSeconds: 10800,
    },
  },
  {
    timestamp: '2021-08-31T17:18:29.510Z',
    type: 'TaskStateEntered',
    id: 86,
    previousEventId: 82,
    stateEnteredEventDetails: { name: 'MitochondrialContentFilter' },
  },
  {
    timestamp: '2021-08-31T17:18:29.510Z',
    type: 'ActivityScheduled',
    id: 87,
    previousEventId: 86,
    activityScheduledEventDetails: {
      resource: 'arn:aws:states:some-region-in-eu:19610412:activity:some-life-pipeline',
      timeoutInSeconds: 10800,
    },
  },
  {
    timestamp: '2021-08-31T17:18:29.520Z',
    type: 'TaskStateEntered',
    id: 88,
    previousEventId: 83,
    stateEnteredEventDetails: { name: 'MitochondrialContentFilter' },
  },
  {
    timestamp: '2021-08-31T17:18:29.520Z',
    type: 'ActivityScheduled',
    id: 89,
    previousEventId: 88,
    activityScheduledEventDetails: {
      resource: 'arn:aws:states:some-region-in-eu:19610412:activity:some-life-pipeline',
      timeoutInSeconds: 10800,
    },
  },
  {
    timestamp: '2021-08-31T17:18:29.552Z',
    type: 'ActivityStarted',
    id: 90,
    previousEventId: 87,
    activityStartedEventDetails: { workerName: 'local' },
  },
  {
    timestamp: '2021-08-31T17:19:03.121Z',
    type: 'ActivitySucceeded',
    id: 91,
    previousEventId: 90,
    activitySucceededEventDetails: {},
  },
  {
    timestamp: '2021-08-31T17:19:03.121Z',
    type: 'TaskStateExited',
    id: 92,
    previousEventId: 91,
    stateExitedEventDetails: { name: 'MitochondrialContentFilter' },
  },
  {
    timestamp: '2021-08-31T17:19:03.121Z',
    type: 'MapIterationSucceeded',
    id: 93,
    previousEventId: 92,
    mapIterationSucceededEventDetails: { name: 'MitochondrialContentFilterMap', index: 1 },
  },
  {
    timestamp: '2021-08-31T17:19:03.254Z',
    type: 'ActivityStarted',
    id: 94,
    previousEventId: 85,
    activityStartedEventDetails: { workerName: 'local' },
  },
  {
    timestamp: '2021-08-31T17:19:31.097Z',
    type: 'ActivitySucceeded',
    id: 95,
    previousEventId: 94,
    activitySucceededEventDetails: {},
  },
  {
    timestamp: '2021-08-31T17:19:31.097Z',
    type: 'TaskStateExited',
    id: 96,
    previousEventId: 95,
    stateExitedEventDetails: { name: 'MitochondrialContentFilter' },
  },
  {
    timestamp: '2021-08-31T17:19:31.097Z',
    type: 'MapIterationSucceeded',
    id: 97,
    previousEventId: 96,
    mapIterationSucceededEventDetails: { name: 'MitochondrialContentFilterMap', index: 0 },
  },
  {
    timestamp: '2021-08-31T17:19:31.208Z',
    type: 'ActivityStarted',
    id: 98,
    previousEventId: 89,
    activityStartedEventDetails: { workerName: 'local' },
  },
  {
    timestamp: '2021-08-31T17:20:01.630Z',
    type: 'ActivitySucceeded',
    id: 99,
    previousEventId: 98,
    activitySucceededEventDetails: {},
  },
  {
    timestamp: '2021-08-31T17:20:01.630Z',
    type: 'TaskStateExited',
    id: 100,
    previousEventId: 99,
    stateExitedEventDetails: { name: 'MitochondrialContentFilter' },
  },
];

module.exports = { fullHistory, singleIterationHistory, noPodsToDeleteHistory };
