const AWS = require('aws-sdk');
// const AWS = require('../utils/requireAWS');

const config = require('../config');

const getRDSEndpoint = async (rdsClient) => {
  // const clusterId = `aurora-cluster-${config.clusterEnv}`;
  const clusterId = 'aurora-cluster-staging';

  // Part of the endpoint's name is a random string generated by rds
  // and we can't control it (it is always the same for accounts)
  // so we can either:
  // - store this random string in S3 or something and fetch it
  // - or ask for an endpoint like I ended up doing here.
  // https://forums.aws.amazon.com/thread.jspa?messageID=486170&#486199
  // https://stackoverflow.com/questions/34990104/rds-endpoint-name-format

  console.log('HOLA3');

  console.log('clusterIdDebug');
  console.log(clusterId);

  const { DBClusterEndpoints: endpoints } = await rdsClient.describeDBClusterEndpoints({
    DBClusterIdentifier: clusterId,
    Filters: [
      { Name: 'db-cluster-endpoint-type', Values: ['writer'] },
      { Name: 'db-cluster-endpoint-status', Values: ['available'] },
    ],
  }).promise();

  console.log('HOLA4');

  if (endpoints.length === 0) {
    throw new Error(`No available endpoints for ${clusterId}`);
  }

  console.log('HOLA5');

  return endpoints[0].Endpoint;
};

const getConnectionParams = async () => {
  if (config.clusterEnv === 'development') {
    return {
      host: '127.0.0.1',
      port: 5432,
      user: 'api_role',
      password: 'postgres', // pragma: allowlist secret
      database: 'aurora_db',
    };
  }

  console.log('HOLA');

  const rdsClient = new AWS.RDS();
  const endpoint = await getRDSEndpoint(rdsClient);
  const username = 'api_role';

  console.log('HOLA1');

  const signer = new AWS.RDS.Signer({
    hostname: endpoint,
    region: config.awsRegion,
    port: 5432,
    username,
  });

  console.log('HOLA6');

  // @ts-ignore
  const token = await signer.getAuthToken().promise();

  console.log('tokenDebug');
  console.log(token);

  console.log('HOLA7');

  // Token expires in 15 minutes https://aws.amazon.com/premiumsupport/knowledge-center/users-connect-rds-iam/
  const tokenExpiration = new Date().getTime() + 15 * 60000;

  console.log('HOLA8');

  console.log('config.clusterEnv');
  console.log(config.clusterEnv);

  console.log('endpointDebug');
  console.log(endpoint);

  return {
    host: endpoint,
    port: 5432,
    user: 'api_role',
    password: token, // pragma: allowlist secret
    database: 'aurora_db',
    expirationChecker: () => tokenExpiration <= Date.now(),
  };
};

module.exports = getConnectionParams;
